---
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build deplyoment script
        run: bash build.sh

      - name: Read built script
        id: getbuiltscript
        run: echo "::set-output name=builtscript::$(cat dist/grab.sh)"

      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: main
          name: "Nightly Release $$"
          prerelease: true
          body: "${{ steps.getbuiltscript.outputs.builtscript }}"
          files: dist/grab.sh
