---
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build deplyoment script
        run: bash build.sh

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: grab.sh
          path: dist/
